### ISSUE TITLE
[CI][GitHub] Approved PR pending to merge list

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#10209]
**Description**
Dear all, we have a list of manually **approved** PR pending on merge (some of them very old). Are you still working on them or can be closed? I understand that, with the manual approval given, only code problems remain. Is anyone working on them?
- [ ] #4076 @swenczowski (old CI)
- [ ] #5658 @RiccardoRossi (old CI)
- [ ] #7128 @adityaghantasala (Failing CI)
- [ ] #7888 @RiccardoRossi (Failing CI)
- [ ] #8302 @peterjwilson :heavy_check_mark: 
- [ ] #8324 @peterjwilson (Failing old centos)
- [ ] #8338 @peterjwilson :heavy_check_mark: 
- [ ] #8968 @Vahid-Galavi (Failing CI) 
- [ ] #9214 @KlausBSautter :heavy_check_mark: 
- [ ] #9390 @salvalatorre (Failing CI, long test) 
- [x] #9579 @marcnunezc (Conflicting file)
- [ ] #9696 @philbucher (conflicts)
- [ ] #9734 @roigcarlo (conflicts) Answering mysefl: I will fix it now.
- [x] #9774 @miguelmaso :heavy_check_mark:
- [x] #9778 @SADPR :heavy_check_mark: 
- [x] #9869 @EduardGomezEscandell :heavy_check_mark: (Draft)
- [ ] #10112 @luzpaz :heavy_check_mark: 
- [ ] #10168 @roigcarlo (Failing CI). This should have not been approved yet
- [x] #10200 @loumalouomega :heavy_check_mark:

**Comment by loumalouomega** [comment]
@roigcarlo #10200 is less than one week old and I am waiting to @RiccardoRossi to take a look (he explicitly said that wanted to take a look)

**Comment by roigcarlo** [comment]
I know, auto-generated list, but it feels wrong to exclude it. (There are also a couple of PR that are pending on me)

**Comment by EduardGomezEscandell** [comment]
https://github.com/KratosMultiphysics/Kratos/pull/9869 will not be merged or worked on any time soon on my side. I don't know if @rubenzorrilla may want to keep it alive. For reference, it tweaks some magic numbers in shock capturing, but last time we worked on this we believed we had deeper implementation issues.
