### ISSUE TITLE
[GeoMechanicsApplication] Couple the thermal element with the water pore pressure Pw

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#10922]
**Description**
The new thermal element needs to be coupled with the pressure, This will be done by means of defining a new coupler, namely, python script.

**TODO**
- [ ] Update/make a new thermal element including advection.
- [ ] Generate a python script in order to couple there processes.
- [ ] Add test cases.
