### ISSUE TITLE
[DEMApplication] Update the DEM inlet options in GiD interface

### ISSUE THREAD

**Issue by ChengshunShang1996** [KratosMultiphysics/Kratos#11113]
**Description**
The DEM inlet options in GiD interface need to be updated.

**TODO**
- [ ] When [Element Type] is set as [Sphere], the correct "ElementType" cannot be written to "ProjectParametersDEM.json".
- [ ] Add [discrete] option to the [Probability distribution]. When we are going to use a self-define particle size distribution, we need this option.
- [ ] Add input parameters for the [discrete] particle distribution.
