### ISSUE TITLE
[GeoMechanicsApplication] Use CoSim to couple pressure and thermal elements.

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#11228]
**Description**
We would like to couple pressure to the newly designed thermal element by CoSim. 

**TODO**
- [ ] Generate two test cases with the same domain and same grid, for pressure and thermal.
- [ ] Test the applications separetely. 
- [ ] Make a test case for CoSimulationApplication in order to couple those cases.
- [ ] If necessary, add scripts/wrapper to CoSimulationApplication for Geo application.
- [ ] Modify the C++ code to add the coupling effects to both sides
- [ ] Run the test case and remove the bugs or inconsistencies.
