### ISSUE TITLE
[GeoMechanicsApplication] Fix the code smells for CoSim branch

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#11542]
**Description**
CoSim branch encountered more than 100 code smells. They are mainly related to redundant comments in the code.
As CoSim branch is not independent (it is branch of a branch), we decided to fix these issues in the master and then merge them back to that branch.

https://github.com/KratosMultiphysics/Kratos/tree/geo/10372-HeatTransfer-temp-branch-cosim

**TODO**
- [ ] Remove code smells from a newly generated branch (from master)
- [ ] Merge it back to master
- [ ] Marge the master to Heat->Cosim branches
