### ISSUE TITLE
[GeoMechanicsApplication] Add the missing conditions to Geomechanics Application for 2D

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#11616]
**Description**
The conditions are not completely added to the GeoMechanics Application. For example, PwCondition is defined on 2 noded element (in 2D) but it is not extended to 3 noded element. There are also missing higher order condition elements in 3D.
Here we fix the 2D conditions. The 3D conditions will be done in a seperate issue in order to keep this commit managable.

**TODO**
- [ ] Add the missing 2D conditions
- [ ] Modify the functions to make them generic for n-th order line elements/conditions
- [ ] Test the implementation
- [ ] If possible, add test cases for the missing conditions.

**Comment by mcgicjn2** [comment]
Can this be broken down into smaller issues and branches for each of the missing conditions ?
