### ISSUE TITLE
[Documentation] Doxygen Takes Forever

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#12255]
I tried running doxygen after a good while and noticed that it takes **forever** to run. I remember something about requiring C++ language parsing (@sunethwarna), but we need to do something about this because it can't even be sped up with multiple threads (by manually overriding `NUM_PROC_THREADS`).

## ToDo

How about this?

Adopt the core/application structure of the source tree: core and each application generate separate doxygen documentations, and produce tag files. If an application depends on another one (or core), link to the related tag file. 

- [x] partition the doxygen doc generation into partitions (core and each application separately)
- [x] build a dependency graph between applications (this could come from CMake)
- [x] run each level of doc generation concurrently (core first, then primary apps depending only on core, then secondary apps depending on other apps, etc.)
- [x] assemble the root docs from core and all apps
