### ISSUE TITLE
[DEMApplication] Servo-loading with periodic boundaries

### ISSUE THREAD

**Issue by ChengshunShang1996** [KratosMultiphysics/Kratos#12666]
**Description**
For applying constant pressure to the DEM sample, we need to establish a servo-loading method with periodic boundaries. Now, a moving periodic boundary has been built in the [DEMApplication]. Only a servo-controlling system is needed to complete this. During the servo-loading process, the mean pressure will be measured periodically to give feedback. 

**TODO**
- [x] Add a new variable for receiving aim pressure from the .json file
- [x] Add a servo-control class in the Python part
- [x] Add a test case
