### ISSUE TITLE
[TODO] [DEM] Establish a rough surface contact model for sperical particle

### ISSUE THREAD

**Issue by ChengshunShang1996** [KratosMultiphysics/Kratos#12881]
**Description**
Based on the work by [M. OTSUBO in 2017](https://www.pure.ed.ac.uk/ws/portalfiles/portal/28248816/Otsubo_et_al_2016_Geotechnique.pdf), the surface roughness effects can at least partially explain the value of the exponent in the relationship between stiffness and mean confining stress for an assembly of spherical particles.

**TODO**

- [ ] Establish this contact model.
- [ ] Verify the implementation.
- [ ] Add a test case.

![Image](https://github.com/user-attachments/assets/cc0ba456-d63b-4547-a59f-f6a1638fcf21)
