### ISSUE TITLE
Identifying utilities to be moved to the MPI core

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#2945]
I am opening this issue to collect Kratos objects (C++ or Python classes, mostly) that should belong to the MPI core. These should be things that call MPI methods directly or that explicitly use tools that have a dependency on MPI. They should not be trilinos-specific (trilinos things will remain on the trilinos application). So far, I have identified the following
- [x] mpi_communicator (currently in kratos core). Done in `experimental/mpi-core` branch
- [x] mpi_python (external libraries). Partially removed in #3821, finally removing the folder in #4215.
- [x] ParallelFillCommunicator (trilinos_application). #5210 
- [x] SetMPICommunicatorProcess (metis_application). Done in `experimental/mpi-core` branch
- [x] the trilinos_gid_output is also a likely candidate (trilinos_application). Removed in #4201 
- [x] GatherModelPartUtility. WIP:  #5355
- [x] custom_gid_io in trlinos application. Removed in #4200.
- [x] mpi_normal_calculation_utilities (trilinos_application). PR #5452.
- [x] trilinos_restart_utility.py Moved in #5243
- [x] trilinos_import_model_part_utility.py Moved in #5243

If anyone can think of something else, please let me know.

Related to #781 

[Last updated on 17.07.19]

**Comment by jcotela** [comment]
@roigcarlo @RiccardoRossi @pooyan-dadvand @philbucher (mentioning since you are heavy MPI users)

**Comment by philbucher** [comment]
GatherModelPartUtility?

**Comment by jcotela** [comment]
Also:
- custom_gid_io in trlinos application :sob: 
- mpi_normal_calculation_utilities (trilinos_application) @loumalouomega is this one still relevant?

**Comment by loumalouomega** [comment]
@jcotela I still have pending to unify all the normal utilities in one, i don't know when i will be able to do it

**Comment by jcotela** [comment]
@loumalouomega  :+1: I just wanted to avoid migrating things if they are already obsolete.

**Comment by loumalouomega** [comment]
probably I will use the MPI one as reference, due to the fact that is the more complex, and then refcactor to make it more general.

**Comment by philbucher** [comment]
python-scripts:
trilinos_restart_utility.py
trilinos_import_model_part_utility.py
With renaming => trilinos -> mpi

**Comment by philbucher** [comment]
I think it would also be good to agree on a name for mpi-files
I think currently we use 3 different names to indicate that a file is related to MPI:
- `*_mpi`
- `*_distributed`
- `*_partitinoned`

**Comment by pooyan-dadvand** [comment]
I would say that if it uses mpi implementation inside to use the `*_mpi`. If is mpi agnostic via DataCommunicator then I would go for `*_distributed`. But I don't have an strong opinion about it.
