### ISSUE TITLE
ToDo PotentialFlow App

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/Kratos#4533]
@KratosMultiphysics/potential-flow-team I am making this ToDo list to have an overview of the upcoming tasks within the CompressiblePotentialFlowApplication. Please feel free to add the tasks you have in mind or modify the list if you think a task or the order of tasks is not suitable.

- [x] Derive the CompressiblePotentialFlowApplication from the FluidDynamicsApplication
- [ ] Migrate python processes to c++
- [ ] Migrate the private functions from the elements and conditions that are not accessing private members to a separate free floating helper functions include and create a test for each one of them.
- [ ] Substitute all Matrix by BoundedMatrix
- [ ] Change the name of the application to PotentialFlowApplication
- [x] Update the GiD interface
- [ ] Find the way to verify the 2D compressible element. XFoil? Other tool? Any ideas?
- [ ] Implement the 2D compressible element
- [ ] Verify the 2D compressible element
- [ ] Implement the 3D incompressible element
- [ ] Verify the 3D incompressible element
- [ ] Implement the 3D compressible element
- [ ] Verify the 3D compressible element
- [x] Implement and verify 2D incompressible sensitivities (pending #4258)
- [ ] Implement and verify 2D compressible sensitivities 
- [ ] Implement and verify 3D incompressible sensitivities
- [ ] Implement and verify 3D compressible sensitivities 
- [ ] Implement and verify 2D incompressible embedded element
- [ ] Implement and verify 2D compressible embedded element
- [ ] Implement and verify 3D incompressible embedded element
- [ ] Implement and verify 3D compressible embedded element
- [ ] Implement and verify embedded sensitivities

**Comment by rubenzorrilla** [comment]
The GiD GUI is working again (https://github.com/KratosMultiphysics/GiDInterface/pull/560 already merged)

**Comment by philbucher** [comment]
are you still using this?

**Comment by inigolcanalejo** [comment]
yes

**Comment by roigcarlo** [comment]
I will close this due to inactivity. 

For tracking issues, please create an specific project in https://github.com/KratosMultiphysics/Kratos/projects?query=is%3Aopen
