### ISSUE TITLE
Next Steps CoSimulation

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5140]
After having accomplished a huge step forward with the merging of the CoSimApp in #5098, here is a list of things that will come next (including my TODO-list)

## Capabilities:
- [x] Coupling to external solvers via => developments on [this branch](https://github.com/KratosMultiphysics/Kratos/compare/cosim/cosim_io) => Using [CoSimIO](https://github.com/KratosMultiphysics/CoSimIO)
- [x] coupling adapter for compatibility to tools that couple to EMPIRE => #5181 & #5248 
- [ ] coupling to OpenFOAM (@navaneethkn)
- [ ] Implement [FMI](https://fmi-standard.org/) (probably not soon but would be very helpful!)

## Applications:
- [x] DEM-FEM coupling (with @KlausBSautter) => #5306 (weak coupling)
- [x] MPM-FEM coupling (with @bodhinandach, following #5110) => #5185 
- [x] Potential Flow FSI (with @inigolcanalejo, following #5022) => #5955 
- [x] Sdof/Mdof solver coupling (with @AndreasWinterstein / @mpentek) => partly in #5837 
- [x] Coupling to Controller (with @AndreasWinterstein / @mpentek), also with MultiCoupling => partly in #5837 

## Other TODOs
- [x] requirements from Gent:
    - [x] make Solvers/ConvAcc/ConvCrit directly usable in python => #5492 / #6006
    - [x] finish the [MappedSolverWrapper](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/solver_wrappers/mapped_solver_wrapper.py)
- [x] related to MPI
    - [x] Check if `IsDistributed` is required for the `SolverWrapper` => no (#9221)
    - [x] properly test in MPI if everything is working => #6006
- [x] testing
    - [x] Add SkipTest to tests in case dependencies are not available => #5152 
    - [x] make tests compatible / executable in MPI
    - [x] create tests with dummy-solvers to check individual components (data-transfer-operators etc)
- [ ] Documentation
    - [x] improve / add description for py-only version => #5158 
    - [ ] add a small description to the Wiki, pointing to the README and the examples
    - [ ] refactor / update the [Examples](https://github.com/KratosMultiphysics/Examples/tree/master/co_simulation/CoSim_DevExamples) to match the new input and structure of the Examples-Repo
    - [x] extend the [README](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/README.md)
- [ ] other things left to do
    - [ ] Go through TODOs in code
    - [x] add deprecation-warning to EmpireApp => #5141 
    - [ ] Address the comments of @rubenzorrilla from #5098 => #5187
    - [x] figure out how to properly integrate the IO => #5248 
    - [ ] make the ConvAcc from the FSI-App useable (requires a small API-change) => #5187
    - [ ] Mapper => how to use `UpdateInterface`? => #8465
    - [x] finish the [copy-operator](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/data_transfer_operators/copy.py) => #5226
    - [x] finish the [distribute-point operation](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/coupling_operations/distribute_point_values.py) and its counterpart => #5993 
    - [ ] finish the [print-iternumber operation](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/coupling_operations/print_iteration_number.py)
    - [x] implement [interval for coupling](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/base_classes/co_simulation_coupled_solver.py#L113-L116) => #5149
    - [x] implement multiplication with factor for coupling-data using the same concept as [in the processes](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/assign_scalar_variable_process.py#L69-L74), e.g. for ramping up or value conversion => #5149 
    - [x] implement global `COSIM_TIME`, `COSIM_STEP` and `COSIM_IS_RESTARTED` as helpers for many things (e.g. in FSI when the Fluid already ran for some time to have a converged solution) => to be implemented as an instance of `ProcessInfo` to be accessed from everywhere in CoSim => #9209
    - [ ] Implement delayed start of solvers (depends on previous point)
    - [ ] Implement restart for CoSim (for now mostly important for accelerators & predictors)
    - [x] port the useful files from the EmpireApp (=> [EmpireMapper](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/EmpireApplication/python_scripts/empire_mapper.py) & [EmpireWrapper](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/EmpireApplication/python_scripts/empire_wrapper.py)) => #5148 
    - [x] some accelerators have not been updated to latest standard, check them ([Anderson](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/convergence_accelerators/anderson.py), [IQN-ILS](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/convergence_accelerators/iqnils.py), [constant-relaxation](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/convergence_accelerators/constant_relaxation.py) => #5492 & #7501)
    - [x] add name to `CouplingInterfaceData` => #5297 
    - [x] Check when to initialize `CouplingInterfaceData`, in the CTor or `Initialize` => can only happen after the Initialize of the Solvers, bcs only then the models are read. The other classes (e.g. conv-acc) however obtain the InterfaceData in the Constructor already, bcs otherwise they'd have to store the SolverWrapper
    - [x] check how to handle the allocation of vars for Kratos => [see here](https://github.com/KratosMultiphysics/Kratos/pull/5185#issuecomment-511363310) => #5297
    - [ ] implement mechanism to check if some operations (e.g. prediction or acceleration) are overwritten by input/output of data (=> maybe by locking-mechanism)
    - [x] use the full ModelPart name including the solver name when constructing the [mapper-tuple](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/data_transfer_operators/kratos_mapping.py#L44-L45) => #5879 
    - [x] implement mechanism to group operations, i.e. if sth is to be applied multiple times on the same InterfaceData (maybe? would be nice to reduce the output in this case?) => probably not possible / too complex
    - [x] use py-mapper factory to also be able to use the py-mappers of the MappingApp => #7432 
    - [ ] rename the sdof transfer operators to sth without "distributed", since this is usually related to MPI
    - [ ] add tests for the ConvergenceAccelerators
    - [ ] add tests for the Predictors
    - [ ] check if the prediction from the Predictors should be done before or after the solvers-prediction
    - [ ] improve performance of ConvergenceAccelerators
    - [x] check behavior of Aitken Convergence Accelerator. The relaxation factors are reported to oscillate a lot. Esp in the first iteration it is apparently very small => should be solved with #6467 
    - [ ] refactor loggers in the long run to use the ones from the Core => how to handle the colors...?
    - [x] make passing of `Model`s from outside to certain solvers possible => #MultiStageSimulation => #7083 
    - [ ] Aitken ConvAcc: make what to use in first iteration selectable (and respect the sign)
    - [ ] Aitken ConvAcc: refactor a bit after #6467
    - [ ] Predictors: maybe compute the prediction at the end of the timestep and then apply it in the next TS predict. This way no larger buffer is needed
    - [ ] Implement higher order predictors

@KratosMultiphysics/cosimulation 

Anyone please feel free to comment if more things should be added

**Comment by philbucher** [comment]
the EmpireApp has now finally been moved to the legacy-apps-repo
All functionalities are ported to the CoSimApp
