### ISSUE TITLE
Roadmap MappingApplication

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7241]
I am describing my goals and future developments for the MappingApplication such that it is more visible for others and to get feedback / initiate a discussion

**Things to be fixed / improved**:
- [ ] Improve searching!
  - [x] Add shared memory parallelism => #9190
  - [x] Improve the algorithm for computing the search radius (using the suggestion of @pooyan-dadvand). This tremendously influences the speed of the mapper construction => #9197
  - [x] Remove the search structure (aka `InterfaceCommunicator`) after searching to save memory. If the interface is updated then anyway everything has to be recomputed  => #9187
  - [ ] improve boundingboxes for search in MPI (low prio)
  - [x] Document the settings => #9197
- [x] check / fix the mapping of non-historical values with `InverseMap` => #9145
- [ ] instead of using the mappingmatrix and hence the Matrix-Vector multiplication I could create GlobalPointers and with the corresponding weight could compute the values => maybe faster? (low prio)
- [ ] try multivectors in Trilinos
- [ ] try other Trilinos options to improve speed
- [ ] shared memory parallel assembly in non-MPI mapping matrix
- [x] Mapping should also be possible with ModelParts that are not disctributed across all ranks => #8515 => #9182

**New Mappers**
- [x] finish the Barycentric mapper (pretty much done but needs to be pushed to master)
- [ ] implement a matching mesh mapper, this seems to be a pretty common use case and there I can do many optimizations
- [x] finish the integration of the empire-mapper => #7452
- [ ] RBF / Mortar mapper => after the other things are done

**Documentation**
- [ ] add an FSI example
- [ ] explain better what each mapper does
- [ ] explain the mapping matrix stuffs
- [ ] explain how output of mapper (e.g. pairingstatus can be used)

FYI @KratosMultiphysics/cosimulation @riccardotosi @roigcarlo @ddiezrod

**Comment by philbucher** [comment]
I did some performance testing regarding the search radius. I knew it was sensitive, but I didn't realize just how sensitive!
It turns out that a non-optimal search radius can decrease the performance tremendously, from << 1 sec to multiple minutes!

The following plot shows for a (matching) mesh with ~13K nodes how bad it can get.

I.e. a large search radius leads to having many search results that all need to be processes (e.g. for nearest neighbor the distance is computed, for nearest element the projection is conducted etc...)
Hence a small number is preferable!

I am working on adding warnings in case too many search results are found such that the user is aware and can manually decrease it.
Please note that the **automatically computed search radius** already gives very good results, and tuning it manually can oftentimes backfire badly

![image](https://user-images.githubusercontent.com/25484702/91334829-d3730b00-e7cf-11ea-8ac7-bbb9e099449b.png)

**Comment by philbucher** [comment]
Doesn’t seem like anyone is going to continue my work
