### ISSUE TITLE
Roadmap ParMmg interface for Release 8.1

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#7728]
**Description**

Opening this issue after #7727, to track the addition of ParMmg interface to the master for next realease.

The branch https://github.com/KratosMultiphysics/Kratos/tree/parmmg_interface_cleanup  contains all needed modifications to use ParMmg within Kratos, as it is done with MMG. [ ParMmg is the MPI parallel version of MMG.](https://github.com/MmgTools/ParMmg/tree/develop)

ParMmg currently only supports 3D volumetric remeshing of tetrahedras

The changes in the branch will be added little by little in small PRs:

**TODO**
- [x] Update assign color utility to add MPI support #7752 
- [x] Add ParMmg cloning and compilation to CI #7754 
- [x] MeshingApp CMakeLists clean up #7812 
- [x] Add ParMmg to CMake to compile Kratos with ParMmg #7790 
- [x] Add pmmg_utililites and pmmg_process #7808 

At this point the ParMMG process should be already fully functional as a python object.

- (after release) Add python pmmg_process.py script 
- (after release) Add pmmg_io
- (after release) Improve test chekcing of mmg/parmmg installations https://github.com/KratosMultiphysics/Kratos/pull/7808#discussion_r528567655
-  (after release) Use MPI from datacommunicator https://github.com/KratosMultiphysics/Kratos/pull/7808#discussion_r544188556

**Comment by marcnunezc** [comment]
Closing this one and continuing in #7990
