### ISSUE TITLE
To-do After Release ParMmg

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#7990]
**Description**
Some pending tasks after #7728 and Release 8.1. 

**TODO**
- [ ] Add python pmmg_process.py script 
- [ ] Add pmmg_io
- [ ] Improve test chekcing of mmg/parmmg installations https://github.com/KratosMultiphysics/Kratos/pull/7808#discussion_r528567655
-  [ ] Use MPI from datacommunicator https://github.com/KratosMultiphysics/Kratos/pull/7808#discussion_r544188556
-  [ ] Check if it is possible to link parmmg/mmg calls in a single python object, redirecting to one another if run is distributed or not. This might allow MMG examples to work with ParMmg without major changes.

**Comment by roigcarlo** [comment]
This is done right?
