### ISSUE TITLE
[Fluid] Wrong level set correction in two-fluids solver

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8346]
**Description**
I've realized that in the two-fluids solver the level set correction is applied to the old level set (i.e. that one that is to be modified by the convection). This happens since the distance correction is applied as a process in the json settings. As these are applied prior to the level set update, that occurs in the `InitializeSolutionStep` of the solver, we are basically doing nothing, which might imply difficulties when solving the local enrichment problem in the element.

In order to prevent this and also to be consistent with the embedded solvers, the distance correction must be done in the `InitializeSolutionStep` of the solver. On top of solving this issue, this avoids the user (or the GUI) to manually set this, allowing thus to provide consistent and robust settings.

@mrhashemi I'd like to hear your opinion about the processes call order. I see these two options:
1) Level set convection
2) Mass correction. Note that right now this is done out of the solver but @uxuech is working on introducing it into the solver (the same problem happens, you want to correct the level set that you are about to use in the N-S resolution)
3) Redistancing
**OPTION A: Distance correction**
4) Distance smoothing
**OPTION B: Distance correction**
5) Surface tension

OPTION A: Would be the best from the curvature perspective, since we ensure that the corrected distance would be always smoothed. However, I'm not sure if such smoothing can deteriorate the level set with ill-conditioned cuts.
OPTION B: Would be the most robust one as we correct the level set just before doing the surface tension and N-S calculations. However, the correction might yield local non-smooth values.

**TODO**
- [x]  Include the distance correction into the `InitializeSolutionStep` after the level set operations of the solver
- [x]  Update the tests json settings
- [ ]  Update the json settings in the Examples repository cases

Pinging all the people that I think might be affected by this: @uxuech @ddiezrod @KratosMultiphysics/altair

**Comment by RiccardoRossi** [comment]
well, we need to be a bit careful with this ordering.

I am not telling that you did not detect an error, simply i wanted to observe that redistancing may also change the volume (although of course it attempts not to)

**Comment by rubenzorrilla** [comment]
> 
> 
> well, we need to be a bit careful with this ordering.
> 
> I am not telling that you did not detect an error, simply i wanted to observe that redistancing may also change the volume (although of course it attempts not to)

Nice one. Then we should discuss:

1) Level set convection
2) Redistancing
3) Mass correction. Note that right now this is done out of the solver but @uxuech is working on introducing it into the solver (the same problem happens, you want to correct the level set that you are about to use in the N-S resolution)
**OPTION A: Distance correction**
4) Distance smoothing
**OPTION B: Distance correction**
5) Surface tension

**Comment by mrhashemi** [comment]
The major point here is that the modification (to prevent the zero-cut) should be done just before calling the element splitting routines (one call is within the NS element and the other one is within mass correction process). 
Meanwhile, there is a chance that both the correction and smoothing processes create a zero-cut. Re-distancing, if used with a careful choice of the option (**in theory**) would not create a zero-cut problem, but **in practice**, it might be dangerous.
What I can suggest here without (Strang) splitting is:
1- re-distancing (in an intermittent manner)
2- level-set
3- smoothing
(distance gradient and curvature can be calculated here since mass correction should (**in theory**) has a limited  effect on the geometrical configuration)
4- mass correction
5- modification

**Comment by rubenzorrilla** [comment]
> The major point here is that the modification (to prevent the zero-cut) should be done just before calling the element splitting routines (one call is within the NS element and the other one is within mass correction process).
> Meanwhile, there is a chance that both the correction and smoothing processes create a zero-cut. Re-distancing, if used with a careful choice of the option (**in theory**) would not create a zero-cut problem, but **in practice**, it might be dangerous.
> What I can suggest here without (Strang) splitting is:
> 1- re-distancing (in an intermittent manner)
> 2- level-set
> 3- smoothing
> (distance gradient and curvature can be calculated here since mass correction should (**in theory**) has a limited effect on the geometrical configuration)
> 4- mass correction
> 5- modification

Considering that the ill-conditioned cuts that might appear prior to the mass correction shouldn't affect the performance of it, this makes sense for me. One thing that seems strange to me is doing the re-distancing before the convection (I assume that step 2- level-set means convection). @mrhashemi which is the rationale behind this change?

**Comment by mrhashemi** [comment]
> > The major point here is that the modification (to prevent the zero-cut) should be done just before calling the element splitting routines (one call is within the NS element and the other one is within mass correction process).
> > Meanwhile, there is a chance that both the correction and smoothing processes create a zero-cut. Re-distancing, if used with a careful choice of the option (**in theory**) would not create a zero-cut problem, but **in practice**, it might be dangerous.
> > What I can suggest here without (Strang) splitting is:
> > 1- re-distancing (in an intermittent manner)
> > 2- level-set
> > 3- smoothing
> > (distance gradient and curvature can be calculated here since mass correction should (**in theory**) has a limited effect on the geometrical configuration)
> > 4- mass correction
> > 5- modification
> 
> Considering that the ill-conditioned cuts that might appear prior to the mass correction shouldn't affect the performance of it, this makes sense for me. One thing that seems strange to me is doing the re-distancing before the convection (I assume that step 2- level-set means convection). @mrhashemi which is the rationale behind this change?

Yes, by _level-set_ I mean convection. The fact is that keeping the level-set function as the real distance is basically needed by the level-set convection. Anyway, if an exactly **zero**-cut occur, the mass correction could have also been failed, therefore, there is an internal check/slight modification for this situation.

**Comment by rubenzorrilla** [comment]
The point is that if we do the redistance before the convection we do not ensure that the levelset is a real function for the gradient calculation... Wouldn't this be problematic? Aside of this, (if I'm not wrong) all the other operations do not violate the real distance property of the levelset so, even though we do the redistance after the convection, the levelset would still be a real distance for the next step convection (which is the rationale behind the current implementation).

**Comment by RiccardoRossi** [comment]
When you convect the levelset you lose the property of it being a distance (norm(grad_phi)=1). The only operation that ensures that we actually get a distance is the "redistance" which unfortunately will cause some minor movements of the zero level set.

on the other hand if you simply add a constant to the levelset function as you would in the case of just shifting it you preserve the distance property

**Comment by mrhashemi** [comment]
One thing that is of major importance is that the level-set convection should be applied to a **real distance**; that is why I propose doing re-distancing at the beginning.
As @RiccardoRossi mentioned, the re-distancing processes that are currently developed also affect the zero-level-set (interface). Therefore, you would not gain anything regarding the distance-gradient (if you manually divide it by its norm that I think is essential even after performing the re-distancing).
Anyway, since we are using an explicit time-marching algorithm, there would not be any big difference if we move the re-distancing.
_The most controversial element of the level-set method is the re-distancing, just consider that it can ruin the contact-angle._

**Comment by rubenzorrilla** [comment]
After a brief final discussion we agreed to do:
In `InitializeSolutionStep`:
1. Levelset convection
2. Smoothing and surface tension requirements
3. Mass correction
4. Distance correction (the last one as the smoothing and mass correction might introduce ill-conditioned cuts)

In `FinalizeSolutionStep`:
1. Re-distancing (very last operation to ensure that the next step convection is done with a "real" distance)

Note: changes should be also applied to the MPI solver.

**Comment by rubenzorrilla** [comment]
Fixed in #8390.
